### ISSUE TITLE
The application closes when selecting sizes.

### ISSUE THREAD

**Issue by experimentator1709** [carina-studio/PixelViewer#1]
Hello.  Does not close in version 1.101

**Comment by carina-studio** [comment]
Hi @experimentator1709 , could you please kindly help to provide the reproduce steps? or provide log file by clicking ```Export application logs...``` in ```About PixelViewer``` dialog? Thanks.

**Comment by experimentator1709** [comment]
Hi! Application closes when selecting .raw file in 1.104
https://drive.google.com/drive/folders/18ZMHIzGx5Iws_44KI7uJLowJBRoP4JjK?usp=sharing



2021-12-13 09:43:55.1351 4124  1    DEBUG App: Created  
2021-12-13 09:43:55.2233 4124  1    WARN  App: Multi-instances server stream created  
2021-12-13 09:43:55.2247 4124  1    WARN  App: Start waiting for multi-instances client  
2021-12-13 09:43:55.3863 4124  1    TRACE HardwareInfo: Dedicated graphics card: True  
2021-12-13 09:43:55.3863 4124  1    DEBUG App: Start loading persistent state  
2021-12-13 09:43:55.3863 4124  1    DEBUG App: Complete loading persistent state  
2021-12-13 09:43:55.3863 4124  13   TRACE ProcessInfo: Private memory usage: 34.9 MB  
2021-12-13 09:43:55.3863 4124  1    DEBUG App: Start loading settings  
2021-12-13 09:43:55.3863 4124  1    DEBUG App: Complete loading settings  
2021-12-13 09:43:55.3965 4124  1    WARN  App: Set log output target to tcp://127.0.0.1:5570  
2021-12-13 09:43:55.3965 4124  1    DEBUG App: Change culture info to ru-RU  
2021-12-13 09:43:55.4406 4124  1    WARN  App: No built-in string resource for ru-RU  
2021-12-13 09:43:55.4406 4124  1    WARN  App: No string resources for ru-RU  
2021-12-13 09:43:56.4713 4124  1    INFO  App: Start checking update  
2021-12-13 09:43:57.9388 4124  1    DEBUG ImageRenderingProfiles: Initialize  
2021-12-13 09:43:57.9629 4124  1    DEBUG ImageRenderingProfiles: 0 user-defined profile(s) loaded  
2021-12-13 09:43:57.9855 4124  1    DEBUG Workspace-1: Create session Session-2, count: 1  
2021-12-13 09:43:57.9855 4124  1    DEBUG Workspace-1: Activate session Session-2  
2021-12-13 09:43:57.9855 4124  1    DEBUG Session-2: Activate  
2021-12-13 09:43:58.0238 4124  1    DEBUG App: Show main window, 1 created  
2021-12-13 09:43:58.0238 4124  1    DEBUG App: Delay for showing splash window  
2021-12-13 09:43:59.8975 4124  1    DEBUG MainWindow: Show application change list dialog  
2021-12-13 09:44:01.9895 4124  1    WARN  MainWindow: All initial dialogs closed  
2021-12-13 09:44:07.1517 4124  1    ERROR App: No application version gotten from package manifest  
2021-12-13 09:44:15.1111 4124  11   DEBUG Session-2: Create source for 'C:\RAW\MotionCam - 4000x3000 RAW10 - OnePlus 8 Pro\frame_439078762073969.raw'  
2021-12-13 09:44:15.1111 4124  11   DEBUG FileImageDataSource: Create source of 'C:\RAW\MotionCam - 4000x3000 RAW10 - OnePlus 8 Pro\frame_439078762073969.raw'  
2021-12-13 09:44:15.1197 4124  1    DEBUG Session-2: Evaluate dimensions of image for 'C:\RAW\MotionCam - 4000x3000 RAW10 - OnePlus 8 Pro\frame_439078762073969.raw'  
2021-12-13 09:44:15.1409 4124  1    DEBUG Session-2: Request 45,8 MB for rendered image, total: 45,8 MB, max: 2,0 GB  
2021-12-13 09:44:15.1409 4124  1    DEBUG Session-2: Render image for 'C:\RAW\MotionCam - 4000x3000 RAW10 - OnePlus 8 Pro\frame_439078762073969.raw', dimensions: 4000x3000  
2021-12-13 09:44:15.2583 4124  1    DEBUG Session-2: Image for 'C:\RAW\MotionCam - 4000x3000 RAW10 - OnePlus 8 Pro\frame_439078762073969.raw' rendered  
2021-12-13 09:44:15.2907 4124  1    ERROR App: ***** Unhandled application exception *****  System.IO.InvalidDataException: Invalid double value
   at Avalonia.Media.PathMarkupParser.ReadDouble(ReadOnlySpan`1& span)
   at Avalonia.Media.PathMarkupParser.ReadPoint(ReadOnlySpan`1& span)
   at Avalonia.Media.PathMarkupParser.AddLine(ReadOnlySpan`1& span, Boolean relative)
   at Avalonia.Media.PathMarkupParser.Parse(String pathData)
   at Avalonia.Media.PathGeometry.Parse(String pathData)
   at Carina.PixelViewer.Controls.BitmapHistogramsView.GenerateHistogramImage(IList`1 histogram, Int32 max, IBrush brush)
   at Carina.PixelViewer.Controls.BitmapHistogramsView.<.ctor>b__22_0()
   at CarinaStudio.Threading.ScheduledAction.ExecuteAction(Object token)
   at CarinaStudio.Threading.ScheduledAction.<>c__DisplayClass12_0.<Schedule>b__0(Object _)
   at CarinaStudio.Threading.SynchronizationContextExtensions.DelayedCallback.CallbackEntry(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at Carina.PixelViewer.App.Main(String[] args)
2021-12-13 09:44:51.5311 16764 1    DEBUG App: Created  
2021-12-13 09:44:51.6143 16764 1    WARN  App: Multi-instances server stream created  
2021-12-13 09:44:51.6153 16764 1    WARN  App: Start waiting for multi-instances client  
2021-12-13 09:44:51.7348 16764 1    TRACE HardwareInfo: Dedicated graphics card: True  
2021-12-13 09:44:51.7348 16764 1    DEBUG App: Start loading persistent state  
2021-12-13 09:44:51.7399 16764 1    DEBUG App: Complete loading persistent state  
2021-12-13 09:44:51.7399 16764 13   TRACE ProcessInfo: Private memory usage: 34.7 MB  
2021-12-13 09:44:51.7399 16764 1    DEBUG App: Start loading settings  
2021-12-13 09:44:51.7399 16764 1    DEBUG App: Complete loading settings  
2021-12-13 09:44:51.7399 16764 1    WARN  App: Set log output target to tcp://127.0.0.1:5570  
2021-12-13 09:44:51.7399 16764 1    DEBUG App: Change culture info to ru-RU  
2021-12-13 09:44:51.7845 16764 1    WARN  App: No built-in string resource for ru-RU  
2021-12-13 09:44:51.7845 16764 1    WARN  App: No string resources for ru-RU  
2021-12-13 09:44:52.7993 16764 1    INFO  App: Start checking update  
2021-12-13 09:44:54.2673 16764 1    DEBUG ImageRenderingProfiles: Initialize  
2021-12-13 09:44:54.2907 16764 1    DEBUG ImageRenderingProfiles: 0 user-defined profile(s) loaded  
2021-12-13 09:44:54.3132 16764 1    DEBUG Workspace-1: Create session Session-2, count: 1  
2021-12-13 09:44:54.3132 16764 1    DEBUG Workspace-1: Activate session Session-2  
2021-12-13 09:44:54.3132 16764 1    DEBUG Session-2: Activate  
2021-12-13 09:44:54.3524 16764 1    DEBUG App: Show main window, 1 created  
2021-12-13 09:44:54.3524 16764 1    DEBUG App: Delay for showing splash window  
2021-12-13 09:44:56.2386 16764 1    DEBUG MainWindow: Show application change list dialog  
2021-12-13 09:44:57.9671 16764 1    WARN  MainWindow: All initial dialogs closed  
2021-12-13 09:45:02.6784 16764 1    ERROR App: No application version gotten from package manifest

**Comment by experimentator1709** [comment]
If the file opens, what settings would you advise me?

**Comment by carina-studio** [comment]
> If the file opens, what settings would you advise me?

Packed RAW10 is not yet supported. You can try using [RAW_SENSOR](https://developer.android.com/reference/android/graphics/ImageFormat?hl=en#RAW_SENSOR) to get picture and use the following prameters:

* Format: One of ```XXXX_16``` Bayer Pattern format.
* Byte-Ordering: ```Little-Endian```.
* Effective bits: ```10```.

**Comment by carina-studio** [comment]
> Hi! Application closes when selecting .raw file in 1.104 https://drive.google.com/drive/folders/18ZMHIzGx5Iws_44KI7uJLowJBRoP4JjK?usp=sharing
> 
> 2021-12-13 09:43:55.1351 4124 1 DEBUG App: Created 2021-12-13 09:43:55.2233 4124 1 WARN App: Multi-instances server stream created 2021-12-13 09:43:55.2247 4124 1 WARN App: Start waiting for multi-instances client 2021-12-13 09:43:55.3863 4124 1 TRACE HardwareInfo: Dedicated graphics card: True 2021-12-13 09:43:55.3863 4124 1 DEBUG App: Start loading persistent state 2021-12-13 09:43:55.3863 4124 1 DEBUG App: Complete loading persistent state 2021-12-13 09:43:55.3863 4124 13 TRACE ProcessInfo: Private memory usage: 34.9 MB 2021-12-13 09:43:55.3863 4124 1 DEBUG App: Start loading settings 2021-12-13 09:43:55.3863 4124 1 DEBUG App: Complete loading settings 2021-12-13 09:43:55.3965 4124 1 WARN App: Set log output target to tcp://127.0.0.1:5570 2021-12-13 09:43:55.3965 4124 1 DEBUG App: Change culture info to ru-RU 2021-12-13 09:43:55.4406 4124 1 WARN App: No built-in string resource for ru-RU 2021-12-13 09:43:55.4406 4124 1 WARN App: No string resources for ru-RU 2021-12-13 09:43:56.4713 4124 1 INFO App: Start checking update 2021-12-13 09:43:57.9388 4124 1 DEBUG ImageRenderingProfiles: Initialize 2021-12-13 09:43:57.9629 4124 1 DEBUG ImageRenderingProfiles: 0 user-defined profile(s) loaded 2021-12-13 09:43:57.9855 4124 1 DEBUG Workspace-1: Create session Session-2, count: 1 2021-12-13 09:43:57.9855 4124 1 DEBUG Workspace-1: Activate session Session-2 2021-12-13 09:43:57.9855 4124 1 DEBUG Session-2: Activate 2021-12-13 09:43:58.0238 4124 1 DEBUG App: Show main window, 1 created 2021-12-13 09:43:58.0238 4124 1 DEBUG App: Delay for showing splash window 2021-12-13 09:43:59.8975 4124 1 DEBUG MainWindow: Show application change list dialog 2021-12-13 09:44:01.9895 4124 1 WARN MainWindow: All initial dialogs closed 2021-12-13 09:44:07.1517 4124 1 ERROR App: No application version gotten from package manifest 2021-12-13 09:44:15.1111 4124 11 DEBUG Session-2: Create source for 'C:\RAW\MotionCam - 4000x3000 RAW10 - OnePlus 8 Pro\frame_439078762073969.raw' 2021-12-13 09:44:15.1111 4124 11 DEBUG FileImageDataSource: Create source of 'C:\RAW\MotionCam - 4000x3000 RAW10 - OnePlus 8 Pro\frame_439078762073969.raw' 2021-12-13 09:44:15.1197 4124 1 DEBUG Session-2: Evaluate dimensions of image for 'C:\RAW\MotionCam - 4000x3000 RAW10 - OnePlus 8 Pro\frame_439078762073969.raw' 2021-12-13 09:44:15.1409 4124 1 DEBUG Session-2: Request 45,8 MB for rendered image, total: 45,8 MB, max: 2,0 GB 2021-12-13 09:44:15.1409 4124 1 DEBUG Session-2: Render image for 'C:\RAW\MotionCam - 4000x3000 RAW10 - OnePlus 8 Pro\frame_439078762073969.raw', dimensions: 4000x3000 2021-12-13 09:44:15.2583 4124 1 DEBUG Session-2: Image for 'C:\RAW\MotionCam - 4000x3000 RAW10 - OnePlus 8 Pro\frame_439078762073969.raw' rendered 2021-12-13 09:44:15.2907 4124 1 ERROR App: ***** Unhandled application exception ***** System.IO.InvalidDataException: Invalid double value at Avalonia.Media.PathMarkupParser.ReadDouble(ReadOnlySpan`1& span) at Avalonia.Media.PathMarkupParser.ReadPoint(ReadOnlySpan`1& span) at Avalonia.Media.PathMarkupParser.AddLine(ReadOnlySpan`1& span, Boolean relative) at Avalonia.Media.PathMarkupParser.Parse(String pathData) at Avalonia.Media.PathGeometry.Parse(String pathData) at Carina.PixelViewer.Controls.BitmapHistogramsView.GenerateHistogramImage(IList`1 histogram, Int32 max, IBrush brush) at Carina.PixelViewer.Controls.BitmapHistogramsView.<.ctor>b__22_0() at CarinaStudio.Threading.ScheduledAction.ExecuteAction(Object token) at CarinaStudio.Threading.ScheduledAction.<>c__DisplayClass12_0.b__0(Object _) at CarinaStudio.Threading.SynchronizationContextExtensions.DelayedCallback.CallbackEntry(Object state) at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg) at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) at Carina.PixelViewer.App.Main(String[] args) 2021-12-13 09:44:51.5311 16764 1 DEBUG App: Created 2021-12-13 09:44:51.6143 16764 1 WARN App: Multi-instances server stream created 2021-12-13 09:44:51.6153 16764 1 WARN App: Start waiting for multi-instances client 2021-12-13 09:44:51.7348 16764 1 TRACE HardwareInfo: Dedicated graphics card: True 2021-12-13 09:44:51.7348 16764 1 DEBUG App: Start loading persistent state 2021-12-13 09:44:51.7399 16764 1 DEBUG App: Complete loading persistent state 2021-12-13 09:44:51.7399 16764 13 TRACE ProcessInfo: Private memory usage: 34.7 MB 2021-12-13 09:44:51.7399 16764 1 DEBUG App: Start loading settings 2021-12-13 09:44:51.7399 16764 1 DEBUG App: Complete loading settings 2021-12-13 09:44:51.7399 16764 1 WARN App: Set log output target to tcp://127.0.0.1:5570 2021-12-13 09:44:51.7399 16764 1 DEBUG App: Change culture info to ru-RU 2021-12-13 09:44:51.7845 16764 1 WARN App: No built-in string resource for ru-RU 2021-12-13 09:44:51.7845 16764 1 WARN App: No string resources for ru-RU 2021-12-13 09:44:52.7993 16764 1 INFO App: Start checking update 2021-12-13 09:44:54.2673 16764 1 DEBUG ImageRenderingProfiles: Initialize 2021-12-13 09:44:54.2907 16764 1 DEBUG ImageRenderingProfiles: 0 user-defined profile(s) loaded 2021-12-13 09:44:54.3132 16764 1 DEBUG Workspace-1: Create session Session-2, count: 1 2021-12-13 09:44:54.3132 16764 1 DEBUG Workspace-1: Activate session Session-2 2021-12-13 09:44:54.3132 16764 1 DEBUG Session-2: Activate 2021-12-13 09:44:54.3524 16764 1 DEBUG App: Show main window, 1 created 2021-12-13 09:44:54.3524 16764 1 DEBUG App: Delay for showing splash window 2021-12-13 09:44:56.2386 16764 1 DEBUG MainWindow: Show application change list dialog 2021-12-13 09:44:57.9671 16764 1 WARN MainWindow: All initial dialogs closed 2021-12-13 09:45:02.6784 16764 1 ERROR App: No application version gotten from package manifest

Cannot reproduce the error by the file you provided and parameters in screenshot, but will check the code. Thanks.

**Comment by carina-studio** [comment]
Now attached RAW image can be opened in ```1.105.0.1220``` successfully with ```Bayer Pattern (10-bit, MIPI)``` format. Workaround for crashing issue is also included in ```1.105.0.1220```.
