### ISSUE TITLE
Failing to run binary 2.7.4.312-arm64 version on Windows 11

### ISSUE THREAD

**Issue by zzambia** [carina-studio/PixelViewer#11]
Platform is Windows 11 on Snapdragon 8cx gen 3.

The executable does not start and this is the content of the log.txt file:

2023-06-05 15:14:23.6315 13668 1    DEBUG App: Created  
2023-06-05 15:14:23.8487 13668 1    TRACE App: [Performance] Took 457 ms to initialize Avalonia framework  
2023-06-05 15:14:23.8778 13668 1    WARN  App: Multi-instances server stream created  
2023-06-05 15:14:23.8778 13668 1    WARN  App: Start waiting for multi-instances client  
2023-06-05 15:14:23.8843 13668 1    DEBUG App: Start loading persistent state  
2023-06-05 15:14:23.8843 13668 1    DEBUG App: Start loading settings  
2023-06-05 15:14:23.9348 13668 1    ERROR HardwareInfo: Failed to check graphics card  System.TypeInitializationException: The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception.
 ---> System.ComponentModel.Win32Exception (193): Failed to load required native library 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll'.
   at System.Management.WmiNetUtilsHelper..cctor()
   --- End of inner exception stack trace ---
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at CarinaStudio.AppSuite.HardwareInfo.CheckGraphicsCard()
2023-06-05 15:14:24.0220 13668 1    ERROR HardwareInfo: Unable to get total physical memory on Windows  System.TypeInitializationException: The type initializer for 'System.Management.WmiNetUtilsHelper' threw an exception.
 ---> System.ComponentModel.Win32Exception (193): Failed to load required native library 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\wminet_utils.dll'.
   at System.Management.WmiNetUtilsHelper..cctor()
   --- End of inner exception stack trace ---
   at System.Management.ThreadDispatch.Start()
   at System.Management.ManagementScope.Initialize()
   at System.Management.ManagementObjectSearcher.Initialize()
   at System.Management.ManagementObjectSearcher.Get()
   at CarinaStudio.AppSuite.HardwareInfo.CheckPhysicalMemory()
2023-06-05 15:14:24.0220 13668 1    WARN  App: This is the first launch  
2023-06-05 15:14:24.0220 13668 1    DEBUG App: Complete loading settings  
2023-06-05 15:14:24.0220 13668 1    DEBUG App: Complete loading persistent state  
2023-06-05 15:14:24.0220 13668 1    WARN  App: Privacy Policy is not agreed yet  
2023-06-05 15:14:24.0220 13668 1    WARN  App: User Agreement is not agreed yet  
2023-06-05 15:14:24.0621 13668 1    DEBUG App: No need to output log to localhost  
2023-06-05 15:14:25.2665 13668 1    INFO  App: Start checking update  
2023-06-05 15:14:25.2665 13668 1    DEBUG JsonPackageResolver: Change state from Initializing to Started

**Comment by hamster620** [comment]
@zzambia I cannot reproduce the error on my Windows 11 running on Apple M1. Could you please help to check the error log in your ```Windows Event Log``` about launching PixelViewer? Thank you.
